name: Build and Upload

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    name: Build the project
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        platform: [linux/amd64]
        # platform: [linux/amd64, linux/arm64] Qemu is not able to build proper ebpf code :/

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup architecture
        id: build-arch
        run: |
          if [ "${{ matrix.platform }}" == "linux/amd64" ]; then
            echo "build_arch=x86_64" >> $GITHUB_OUTPUT
          elif [ "${{ matrix.platform }}" == "linux/arm64" ]; then
            echo "build_arch=arm64" >> $GITHUB_OUTPUT
          fi

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Setup Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ steps.build-arch.outputs.build_arch }}-${{ github.sha }}
          upload-chunk-size: 1000000
          restore-keys: |
            ${{ runner.os }}-docker-${{ steps.build-arch.outputs.build_arch }}-
            ${{ runner.os }}-docker-
            ${{ runner.os }}-

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_USERPASS }}

      - name: Build Image and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          load: true
          platforms: ${{ matrix.platform }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          tags: criblio/scope-ebpf:next

      - name: Create Container
        run: docker create --name scope_release_${{ steps.build-arch.outputs.build_arch }} --platform ${{ matrix.platform }} criblio/scope-ebpf:next

      - name: Copy the build from container
        run: docker cp scope_release_${{ steps.build-arch.outputs.build_arch }}:/bin/scope-ebpf /tmp/scope-ebpf-${{ steps.build-arch.outputs.build_arch }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: scope-ebpf
          path: /tmp/scope-ebpf-${{ steps.build-arch.outputs.build_arch }}
